-- CreateTable
CREATE TABLE "news_feed" (
    "id" SERIAL NOT NULL,
    "request_id" INTEGER NOT NULL,
    "companyname" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "insider" TEXT NOT NULL,
    "outsider" TEXT NOT NULL,
    "ceo" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "date" TEXT NOT NULL,
    "company_rel" INTEGER NOT NULL,
    "insider_rel" INTEGER NOT NULL,
    "outsider_rel" INTEGER NOT NULL,
    "ceo_rel" INTEGER NOT NULL,
    "company_sentiment" DOUBLE PRECISION NOT NULL,
    "insider_sentiment" DOUBLE PRECISION,
    "outsider_sentiment" DOUBLE PRECISION,
    "ceo_sentiment" DOUBLE PRECISION,
    "GHG_emissions_similarity" DOUBLE PRECISION NOT NULL,
    "GHG_emissions_sentiment" DOUBLE PRECISION,
    "Air_quality_similarity" DOUBLE PRECISION NOT NULL,
    "Air_quality_sentiment" DOUBLE PRECISION,
    "Energy_management_similarity" DOUBLE PRECISION NOT NULL,
    "Energy_management_sentiment" DOUBLE PRECISION,
    "Water_wastewater_management_similarity" DOUBLE PRECISION NOT NULL,
    "Water_wastewater_management_sentiment" DOUBLE PRECISION,
    "Waste_hazardous_management_similarity" INTEGER NOT NULL,
    "Waste_hazardous_management_sentiment" DOUBLE PRECISION,
    "Ecological_impact_similarity" INTEGER NOT NULL,
    "Ecological_impact_sentiment" DOUBLE PRECISION,
    "Human_rights_community_similarity" DOUBLE PRECISION NOT NULL,
    "Human_rights_community_sentiment" DOUBLE PRECISION,
    "Customer_privacy_similarity" DOUBLE PRECISION NOT NULL,
    "Customer_privacy_sentiment" DOUBLE PRECISION,
    "Data_security_similarity" INTEGER NOT NULL,
    "Data_security_sentiment" DOUBLE PRECISION,
    "Access_affordability_similarity" DOUBLE PRECISION NOT NULL,
    "Access_affordability_sentiment" DOUBLE PRECISION,
    "Product_quality_safety_similarity" INTEGER NOT NULL,
    "Product_quality_safety_sentiment" DOUBLE PRECISION,
    "Customer_welfare_similarity" INTEGER NOT NULL,
    "Customer_welfare_sentiment" DOUBLE PRECISION,
    "Selling_practices_product_label_similarity" DOUBLE PRECISION NOT NULL,
    "Selling_practices_product_label_sentiment" DOUBLE PRECISION,
    "Labor_practices_similarity" DOUBLE PRECISION NOT NULL,
    "Labor_practices_sentiment" DOUBLE PRECISION,
    "Modern_slavery_similarity" DOUBLE PRECISION NOT NULL,
    "Modern_slavery_sentiment" DOUBLE PRECISION,
    "Employee_health_safety_similarity" INTEGER NOT NULL,
    "Employee_health_safety_sentiment" DOUBLE PRECISION,
    "Employee_engagement_diversity_similarity" INTEGER NOT NULL,
    "Employee_engagement_diversity_sentiment" DOUBLE PRECISION,
    "Gender_equality_similarity" INTEGER NOT NULL,
    "Gender_equality_sentiment" DOUBLE PRECISION,
    "Product_design_lifecycle_similarity" DOUBLE PRECISION NOT NULL,
    "Product_design_lifecycle_sentiment" DOUBLE PRECISION,
    "Business_model_resilience_similarity" DOUBLE PRECISION NOT NULL,
    "Business_model_resilience_sentiment" DOUBLE PRECISION,
    "Environmental_supply_chain_similarity" DOUBLE PRECISION NOT NULL,
    "Environmental_supply_chain_sentiment" DOUBLE PRECISION,
    "Social_supply_chain_similarity" DOUBLE PRECISION NOT NULL,
    "Social_supply_chain_sentiment" DOUBLE PRECISION,
    "Materials_sourcing_efficiency_similarity" DOUBLE PRECISION NOT NULL,
    "Materials_sourcing_efficiency_sentiment" DOUBLE PRECISION,
    "Physical_impacts_climate_change_similarity" INTEGER NOT NULL,
    "Physical_impacts_climate_change_sentiment" DOUBLE PRECISION,
    "Governance_structures_similarity" DOUBLE PRECISION NOT NULL,
    "Governance_structures_sentiment" DOUBLE PRECISION,
    "Business_ethics_similarity" DOUBLE PRECISION NOT NULL,
    "Business_ethics_sentiment" DOUBLE PRECISION,
    "Competitive_behavior_similarity" DOUBLE PRECISION NOT NULL,
    "Competitive_behavior_sentiment" DOUBLE PRECISION,
    "Management_legal_regulatory_similarity" DOUBLE PRECISION NOT NULL,
    "Management_legal_regulatory_sentiment" DOUBLE PRECISION,
    "Risk_management_similarity" DOUBLE PRECISION NOT NULL,
    "Risk_management_sentiment" DOUBLE PRECISION,
    "Coronavirus_similarity" DOUBLE PRECISION NOT NULL,
    "Coronavirus_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_1_similarity" DOUBLE PRECISION NOT NULL,
    "Sustainable_Development_Goal_1_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_2_similarity" DOUBLE PRECISION NOT NULL,
    "Sustainable_Development_Goal_2_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_3_similarity" DOUBLE PRECISION NOT NULL,
    "Sustainable_Development_Goal_3_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_4_similarity" DOUBLE PRECISION NOT NULL,
    "Sustainable_Development_Goal_4_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_5_similarity" DOUBLE PRECISION NOT NULL,
    "Sustainable_Development_Goal_5_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_6_similarity" INTEGER NOT NULL,
    "Sustainable_Development_Goal_6_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_7_similarity" DOUBLE PRECISION NOT NULL,
    "Sustainable_Development_Goal_7_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_8_similarity" DOUBLE PRECISION NOT NULL,
    "Sustainable_Development_Goal_8_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_9_similarity" DOUBLE PRECISION NOT NULL,
    "Sustainable_Development_Goal_9_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_10_similarity" DOUBLE PRECISION NOT NULL,
    "Sustainable_Development_Goal_10_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_11_similarity" DOUBLE PRECISION NOT NULL,
    "Sustainable_Development_Goal_11_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_12_similarity" DOUBLE PRECISION NOT NULL,
    "Sustainable_Development_Goal_12_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_13_similarity" DOUBLE PRECISION NOT NULL,
    "Sustainable_Development_Goal_13_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_14_similarity" INTEGER NOT NULL,
    "Sustainable_Development_Goal_14_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_15_similarity" DOUBLE PRECISION NOT NULL,
    "Sustainable_Development_Goal_15_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_16_similarity" DOUBLE PRECISION NOT NULL,
    "Sustainable_Development_Goal_16_sentiment" DOUBLE PRECISION,
    "Sustainable_Development_Goal_17_similarity" INTEGER NOT NULL,
    "Sustainable_Development_Goal_17_sentiment" DOUBLE PRECISION,
    "Controversial_weapons_similarity" INTEGER NOT NULL,
    "Controversial_weapons_sentiment" DOUBLE PRECISION,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "news_feed_pkey" PRIMARY KEY ("id")
);
